[tool.poetry]
name = "superdebug"
version = "0.1.0"
description = "Convenient debugging for machine learning projects"
authors = ["Azure-Vision <hewanrong2001@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
mypyc-ipython = "^0.0.2"
Pillow = "^9.0.1"
torch = "^1.11.0"
numpy = "^1.22.3"
torchvision = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
